env:
    browser: true
    es6: true
    node: true
extends:
    - 'react-app'
    - 'plugin:jsx-a11y/recommended'
    - 'eslint:recommended'
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 2018
    sourceType: module
plugins:
    - 'jsx-a11y'
    - 'react'
rules:
    comma-style:
        - error
        - last
    indent:
        - error
        - 4
        - SwitchCase: 1
          VariableDeclarator: 1
          MemberExpression: 0
          FunctionDeclaration:
              body: 1
              parameters: off
          FunctionExpression:
              body: 1
              parameters: off
    linebreak-style:
        - error
        - unix
    max-len:
        - error
        - code: 80
    no-multiple-empty-lines:
        - error
        - max: 1
          maxBOF: 0
    no-trailing-spaces:
        - error
        - skipBlankLines: true
    quotes:
        - error
        - single
    semi:
        - error
        - always
    space-before-blocks:
        - error
        - never

